[2021-07-08 07:17:12,749] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: batch.pythonoperator 2020-07-01T07:15:00+00:00 [queued]>
[2021-07-08 07:17:12,764] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: batch.pythonoperator 2020-07-01T07:15:00+00:00 [queued]>
[2021-07-08 07:17:12,764] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-08 07:17:12,764] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-07-08 07:17:12,765] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-08 07:17:12,771] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): pythonoperator> on 2020-07-01T07:15:00+00:00
[2021-07-08 07:17:12,777] {standard_task_runner.py:52} INFO - Started process 51907 to run task
[2021-07-08 07:17:12,781] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'batch', 'pythonoperator', '2020-07-01T07:15:00+00:00', '--job-id', '1631', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Batch_test_operators.py', '--cfg-path', '/tmp/tmp8k79hsp4', '--error-file', '/tmp/tmp_4q6nd4i']
[2021-07-08 07:17:12,783] {standard_task_runner.py:77} INFO - Job 1631: Subtask pythonoperator
[2021-07-08 07:17:12,819] {logging_mixin.py:104} INFO - Running <TaskInstance: batch.pythonoperator 2020-07-01T07:15:00+00:00 [running]> on host e4c2a6f3dcfb
[2021-07-08 07:17:12,874] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=batch
AIRFLOW_CTX_TASK_ID=pythonoperator
AIRFLOW_CTX_EXECUTION_DATE=2020-07-01T07:15:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-07-01T07:15:00+00:00
[2021-07-08 07:17:12,875] {logging_mixin.py:104} INFO - ============================================================
[2021-07-08 07:17:12,875] {logging_mixin.py:104} INFO - seconds:10
[2021-07-08 07:17:12,875] {logging_mixin.py:104} INFO - ============================================================
[2021-07-08 07:17:12,875] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.6/dist-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.6/dist-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/pyspark/airflow/dags/Batch_test_operators.py", line 30, in sleep_seconds
    pprint(kwargs)
NameError: name 'pprint' is not defined
[2021-07-08 07:17:12,876] {taskinstance.py:1531} INFO - Marking task as FAILED. dag_id=batch, task_id=pythonoperator, execution_date=20200701T071500, start_date=20210708T071712, end_date=20210708T071712
[2021-07-08 07:17:12,911] {local_task_job.py:151} INFO - Task exited with return code 1
